# Header
navname: 白鲸字幕组官网

# navigatior items
nav:
  旗下账号: /accounts
  成员: /members
  关于: /about
  加入: /join-us
  商业合作: /business

# favicon
favicon: /favicon.ico

# Profile
nickname: 白鲸字幕组

### this variable is MarkDown form.
description: 白鲸字幕组是一个非盈利性质的多语言字幕组。<br><br>我们旨在为身处中国大陆的粉丝们提供<br>优质字幕、精准翻译、光速搬运
avatar: https://r2.img.zla.app/2024/12/02/fcc241.webp

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  # Blog:
  # Category:
  # Tags:
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS: /atom.xml
  # AliPay:
  # ZhiHu:
  # LinkedIn:
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  # Weibo: https://weibo.com/n/%E7%99%BD%E9%B2%B8%E5%AD%97%E5%B9%95%E7%BB%84
  # Email: emailto:admin@belugasubs.com
  # WeChat:
  # Github:

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: false
post_date_enable: true
post_category_enable: false
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: false
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2019-<span id="copyright-current-year"></span> <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: false
post_copyright_slogan_text: Beluga Subs
## toc
post_toc_enable: true

# Page title
page_title_enable: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - https://unpkg.com/leaflet@1.7.1/dist/leaflet.css # 引入 Leaflet 地图库的 CSS
  - /css/style.css
  - /assets/custom.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
  - https://unpkg.com/leaflet@1.7.1/dist/leaflet.js # 引入 Leaflet 地图库的 JavaScript
  - https://d3js.org/d3-dsv.v1.min.js # 引入 D3.js 库来解析 CSV 文件
  - /js/custom.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot

# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: false
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter
